ARG FRAPPE_BRANCH=develop
FROM frappe/erpnext-worker:${FRAPPE_BRANCH}

RUN install_app naufaltheme https://github.com/naufalfathur/naufaltheme main && \
  install_app whitelabel https://github.com/bhavesh95863/whitelabel master && \

